# Generated by Django 4.0.3 on 2022-04-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='arquivo_final',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('C', 'Em criação'), ('AA', 'Aguardando aprovação'), ('F', 'Finalizado')], default='C', max_length=2),
        ),
    ]
